import Head from 'next/head'
import Banner from '@/components/Banner'
import Image from 'next/image'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Indomino Farms</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" sizes="180x180" href="/indominologo.ico" />
      </Head>
      <main>
        <Banner/>
        <p>Indomino farms</p>
      </main>
    </div>
  )
}
